"""Regenerate the Hair Room section of menu.html from one price table.

Hand-typing ~45 price rows invites a wrong digit, so the data lives here once and
the markup is generated. Run again after any price change.

Price forms:
  75            -> "$75"
  "95+"         -> "$95+"   ("+" hidden from screen readers, replaced with "and up")
  (130, 255)    -> "$130 - $255"  (dash hidden, replaced with "to")
  (120, 320, "per 100g")
"""
import re
from pathlib import Path

# Resolved relative to this script, so moving the project does not break it.
MENU = Path(__file__).resolve().parent.parent / "menu.html"

# --- from the salon's printed Hair Room menu -------------------------------
HAIR_SERVICES = [("Silk Press", 75), ("Cut, Blow &amp; Style", 55), ("Color", "95+")]
EXTENSIONS    = [("Tape-In", "200+"), ("Sew-In", "180+"), ("Micro Links", "220+")]

# --- from the supplied price tables ----------------------------------------
BRAIDS = [
    ("Box Braids", "180+"),                # printed menu price, kept over the table's $130-255
    ("Knotless Box Braids", (145, 350)),
    ("Boho Knotless Braids", (185, 400)),
    ("Goddess Braids", "175+"),            # printed menu price, kept over the table's $140-365
    ("Feed-In / Stitch Braids", (65, 200)),
    ("Cornrows (no extensions)", (30, 85)),
    ("Cornrows (with extensions)", (45, 160)),
    ("Fulani / Tribal Braids", (120, 250)),
    ("Lemonade Braids", (95, 150)),
    ("Micro Braids", "275+"),          # printed menu only; absent from the new table
    ("Kids Braids", (55, 125)),
]
TWISTS = [
    ("Senegalese Twists", (165, 235)),
    ("Passion Twists", (165, 210)),
    ("Kinky Twists", (160, 235)),
    ("Micro Twists", (180, 315)),
    ("Flat Twists (natural)", (65, 85)),
    ("Block Twist / Twist", "120+"),   # printed menu only
]
LOCS = [
    ("Faux Locs", (185, 275)),
    ("Butterfly Locs", (170, 250)),
    ("Goddess Locs", (200, 300)),
    ("Invisible Locs", (185, 300)),
    ("Starter Locs / Coil", (50, 120)),
    ("Loc Retwist / Maintenance", (65, 120)),
    ("Loc Detox", (80, 150)),
    ("Microlocs (natural hair)", (1400, 1800)),
    ("Microlocs (with extensions)", (1900, 3200)),
    ("Microlocs Retie", (250, 300)),
]
CROCHET = [
    ("Crochet Braids", (80, 150)),
    ("Crochet Faux / Butterfly Locs", (95, 210)),
    ("Crochet Goddess Locs", (100, 220)),
]
# Cost of the hair itself, NOT the service to install it.
HAIR_COST = [
    ("Clip-in", (50, 400)),
    ("Tape-in", (120, 320, "per 100g")),
    ("Sew-in / Weave", (100, 600)),
    ("Micro-link / Micro-bead", (200, 600)),
    ("Fusion / Pre-bonded (keratin)", (200, 800)),
    ("Halo / Wire", (100, 350)),
    ("Ponytail extension", (80, 250)),
]


def price_html(p):
    if isinstance(p, tuple):
        lo, hi = p[0], p[1]
        suffix = f'<span class="text-muted font-normal text-xs"> {p[2]}</span>' if len(p) > 2 else ''
        return (f'${lo:,}<span class="sr-only"> to </span>'
                f'<span aria-hidden="true"> &ndash; </span>${hi:,}{suffix}')
    if isinstance(p, str) and p.endswith('+'):
        return f'${p[:-1]}<span aria-hidden="true">+</span><span class="sr-only"> and up</span>'
    return f'${p}'


def rows(items):
    return '\n'.join(
        f'          <div><dt>{n}</dt><dd class="text-champagne font-semibold">{price_html(p)}</dd></div>'
        for n, p in items)


def card(anchor, title, items, surface='bg-charcoal'):
    return f'''      <article id="{anchor}" class="reveal card-hover {surface} border border-cream/10 rounded-2xl p-7 sm:p-8" aria-labelledby="{anchor}-title">
        <h3 id="{anchor}-title" class="font-display text-2xl font-semibold">{title}</h3>
        <div class="w-10 h-px bg-champagne/60 mt-3 mb-4" aria-hidden="true"></div>
        <dl class="price-list">
{rows(items)}
        </dl>
      </article>'''


section = f'''<!-- HAIR ROOM — generated by scripts/build_menu.py; edit the prices there, not here.
     A "+" is a starting price and is hidden from screen readers in favour of
     "and up"; a range's dash is likewise replaced with "to". -->
<section id="hair-room" class="py-20 md:py-24 px-6 hairline bg-surface" aria-labelledby="hair-room-title">
  <div class="max-w-6xl mx-auto">
    <div class="reveal text-center mb-12">
      <h2 id="hair-room-title" class="font-display text-4xl md:text-[2.75rem] font-semibold mb-5">Hair Room</h2>
      <div class="ornament max-w-[14rem] mx-auto" aria-hidden="true"><span></span></div>
    </div>

    <div class="grid gap-6 max-w-xl mx-auto lg:max-w-5xl lg:grid-cols-2 lg:gap-8 items-start">

{card('hair-services', 'Hair Services', HAIR_SERVICES)}

{card('braids', 'Braids', BRAIDS)}

{card('twists', 'Twists', TWISTS)}

{card('locs', 'Locs &amp; Dreadlocks', LOCS)}

{card('crochet', 'Crochet', CROCHET)}

{card('extensions', 'Hair Extensions', EXTENSIONS)}

    </div>

    <p class="reveal text-center font-display text-muted mt-10">Consultations available.</p>

    <!-- Cost of the hair itself, kept apart from the service prices above so the
         two can never be read as one number. -->
    <div class="reveal max-w-2xl mx-auto mt-14">
      <article id="hair-cost" class="bg-charcoal border border-champagne/25 rounded-2xl p-7 sm:p-8" aria-labelledby="hair-cost-title">
        <h3 id="hair-cost-title" class="font-display text-2xl font-semibold">Hair Supplied by the Salon</h3>
        <div class="w-10 h-px bg-champagne/60 mt-3 mb-4" aria-hidden="true"></div>
        <p class="text-sm text-muted mb-5">What the hair itself costs. This is separate from the styling price above.</p>
        <dl class="price-list">
{rows(HAIR_COST)}
        </dl>
      </article>
    </div>
  </div>
</section>

'''

CHIPS = [('hair-services', 'Hair Services'), ('braids', 'Braids'), ('twists', 'Twists'),
         ('locs', 'Locs'), ('crochet', 'Crochet'), ('extensions', 'Extensions'),
         ('hair-cost', 'Hair Cost'), ('makeup', 'Makeup'), ('skincare', 'Skincare')]
chip_cls = ("btn-hover min-h-[44px] inline-flex items-center px-5 rounded-full border "
            "border-cream/20 text-sm font-medium hover:border-champagne hover:text-champagne")
chips = '\n'.join(f'      <a href="#{a}" class="{chip_cls}">{t}</a>' for a, t in CHIPS)

html = MENU.read_text(encoding='utf-8')

# 1) replace the whole Hair Room section
start = html.index('<!-- HAIR ROOM')
end = html.index('<!-- FACIAL ROOM -->')
html = html[:start] + section + html[end:]

# 2) replace the jump chips
html = re.sub(r'(<nav aria-label="Menu sections"[^>]*>\n).*?(\n    </nav>)',
              lambda m: m.group(1) + chips + m.group(2), html, flags=re.S)

# 3) legend under the chips
old_legend = re.search(r'    <p class="text-sm text-muted">\n.*?\n    </p>', html, re.S).group(0)
new_legend = '''    <p class="text-sm text-muted">
      All services by appointment <span aria-hidden="true" class="mx-2 text-champagne">·</span>
      a <span class="text-champagne font-semibold">+</span> marks a starting price
    </p>'''
html = html.replace(old_legend, new_legend)

MENU.write_text(html, encoding='utf-8')

n = sum(len(x) for x in (HAIR_SERVICES, BRAIDS, TWISTS, LOCS, CROCHET, EXTENSIONS, HAIR_COST))
print(f'wrote {MENU.name}: {n} price rows across 7 lists')
